version: '3'

services:

  neo4j:
    image: neo4j
    container_name: cloud-neo4j

    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    env_file:
      - "./env/$ENV.env"
    volumes:
      - ./docker/neo4j/plugins:/var/lib/neo4j/plugins
      - ./docker/neo4j/data:/data/rdf
      - ./docker/neo4j/config/apoc.conf:/var/lib/neo4j/conf/apoc.conf

  postgres: 
    image: postgres
    container_name: cloud-postgres
    env_file:
      - "./env/$ENV.env"
    expose:
      - 5432

  cache:
    image: redis
    container_name: cloud-cache

  logging:
    build: 
      context: .
      dockerfile: ./docker/logging/Dockerfile
    image: cloud-logging
    container_name: cloud-logging

  s3:
    build:
      context: .
      dockerfile: ./docker/s3/Dockerfile
    image: cloud-s3
    volumes:
      - ./docker/s3/data:/data/data
    container_name: cloud-s3
    ports:
      - 800:80

  lb:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile    
    image: cloud-lb
    container_name: cloud-lb
    ports:
      - 80:80
    depends_on:
      - app-be
      # - app-fe
    links: 
      - app-be
      # - app-fe

  app-fe:
    build: 
      context: .
      dockerfile: ./docker/app-fe/Dockerfile
    image: cloud-fe
    ports:
      - 3000:3000
    container_name: cloud-fe
    env_file:
      - "./env/$ENV.env"
    links: 
      - lb
      - s3
      - logging

  app-be:
    build: 
      context: .
      dockerfile: ./docker/app-be/Dockerfile
    image: cloud-be
    container_name: cloud-be
    env_file:
      - "./env/$ENV.env"
    environment:
      - OPTIMIZED=$OPTIMIZED
    depends_on:
      - neo4j
      - postgres
      - cache
    links: 
      - postgres
      - neo4j
      - cache
      # - logging
    restart: on-failure # We add this because neo4j initialization time take to much time

  # local-app-fe:
  #     build: 
  #       context: .
  #       dockerfile: ./docker/app-fe/Dockerfile
  #     command: ["npm", "start"]
  #     container_name: tplogistic-local-app-fe
  #     ports:
  #     - 6000:6000
  #     env_file:
  #       - "./env/$ENV.env"
  #     depends_on:
  #       - local-app-be
  #     links: 
  #       - local-app-be