version: '3'

services:
  db: 
    image: postgres
    container_name: tplogistic-db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis
    container_name: tplogistic-cache
    ports:
      - 6379:6379

  app-be:
    build: 
      context: .
      dockerfile: ./docker/app-be/Dockerfile
    command: ["npm", "run", "start"]
    env_file:
      - "./env/$ENV.env"
    depends_on:
      - db
      - cache
    links: 
      - db
      - cache
      - logging

  local-app-be:
    build: 
      context: .
      dockerfile: ./docker/app-be/Dockerfile
    command: ["npm", "run", "start"]
    container_name: tplogistic-local-app-be
    ports:
      - 3000:3000
    env_file:
      - "./env/$ENV.env"
    depends_on:
      - db
      - cache
    links: 
      - db
      - cache
      - logging

  app-fe:
    build: 
      context: .
      dockerfile: ./docker/app-fe/Dockerfile
    command: ["npm", "start"]
    env_file:
      - "./env/$ENV.env"
    depends_on:
      - app-be
    links: 
      - app-be

  local-app-fe:
      build: 
        context: .
        dockerfile: ./docker/app-fe/Dockerfile
      command: ["npm", "start"]
      container_name: tplogistic-local-app-fe
      ports:
      - 5000:5000
      env_file:
        - "./env/$ENV.env"
      depends_on:
        - local-app-be
      links: 
        - local-app-be

  lb:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile    
    container_name: tplogistic-lb
    ports:
      - 80:80
    depends_on:
      - app-be
      - app-fe
    links: 
      - app-be
      - app-fe

  logging:
    build:
      context: .
      dockerfile: ./docker/logging/Dockerfile
    container_name: tplogistic-logging